SITE_NAME="BirdNET-Dev"
LATITUDE=50.0000
LONGITUDE=5.0000
MODEL=Perch_v2
SF_THRESH=0.03
DATA_MODEL_VERSION=1
PERCH_BIRDNET_FILTER=1
BIRDWEATHER_ID=
CADDY_PWD=dev
ICE_PWD=birdnetpi
BIRDNETPI_URL=
RTSP_STREAM=
RTSP_STREAM_TO_LIVESTREAM="0"
APPRISE_NOTIFICATION_TITLE="New BirdNET-Pi Detection"
APPRISE_NOTIFY_EACH_DETECTION=0
APPRISE_NOTIFY_NEW_SPECIES=0
APPRISE_WEEKLY_REPORT=0
APPRISE_NOTIFY_NEW_SPECIES_EACH_DAY=0
APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES=0
APPRISE_ONLY_NOTIFY_SPECIES_NAMES=""
APPRISE_ONLY_NOTIFY_SPECIES_NAMES_2=""
IMAGE_PROVIDER=WIKIPEDIA
FLICKR_API_KEY=
FLICKR_FILTER_EMAIL=
INFO_SITE="ALLABOUTBIRDS"
COLOR_SCHEME="light"
FULL_DISK=purge
PURGE_THRESHOLD=95
MAX_FILES_SPECIES=0
BIRDNET_USER=birdnet
RECS_DIR=/home/birdnet/BirdSongs
PROCESSED=/home/birdnet/BirdSongs/Processed
EXTRACTED=/home/birdnet/BirdSongs/Extracted
REC_CARD=default
OVERLAP=0.0
CONFIDENCE=0.7
SENSITIVITY=1.25
FREQSHIFT_TOOL=sox
FREQSHIFT_HI=6000
FREQSHIFT_LO=3000
FREQSHIFT_RECONNECT_DELAY=4000
FREQSHIFT_PITCH=-1500
CHANNELS=2
PRIVACY_THRESHOLD=0
RECORDING_LENGTH=15
EXTRACTION_LENGTH=
AUDIOFMT=mp3
DATABASE_LANG=en
HEARTBEAT_URL=
SILENCE_UPDATE_INDICATOR=0
AUTOMATIC_UPDATE=0
RAW_SPECTROGRAM=0
CUSTOM_IMAGE=
CUSTOM_IMAGE_TITLE=""
RARE_SPECIES_THRESHOLD=30
TARGET_SCORE_LOGGING=1
TARGET_SCORE_MAX_FILE_MB=200
ACTIVATE_FREQSHIFT_IN_LIVESTREAM=0
LAST_RUN=
THIS_RUN=
IDFILE=/home/birdnet/BirdNET-Pi/IdentifiedSoFar.txt
LogLevel_BirdnetRecordingService="error"
LogLevel_LiveAudioStreamService="error"
LogLevel_SpectrogramViewerService="error"
